name: Build & Deploy to Digital Ocean
on:
  push:
    branches: [main]
    
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Deploy App
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}}
        password: ${{secrets.SSH_PASSWORD}}
        username: ${{secrets.SSH_USER}}

        script: |
          cd ../home/actions-test
          git pull
          echo 'pulled form repo'
          yarn install
          echo 'installed dependencies'
