name: Build & Deploy to Digital Ocean
on:
  push:
    branches: [main]
    
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@master
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Deploy App
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}}
        password: ${{secrets.SSH_PASSWORD}}
        username: ${{secrets.SSH_USER}}

        script: |
          cd ../home/actions-test
          git pull
          echo 'pulled form repo'
          yarn install
          echo 'installed dependencies'
